"""add expired booking status

Revision ID: 06b9c9a18716
Revises: 7dc3b139775b
Create Date: 2026-09-17 20:16:37.560381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from alembic_postgresql_enum.sql_commands.indexes import TableIndex

# revision identifiers, used by Alembic.
revision: str = '06b9c9a18716'
down_revision: Union[str, Sequence[str], None] = '7dc3b139775b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='bookingstatus',
        new_values=['pending_payment', 'pending_approval', 'confirmed', 'active', 'completed', 'cancelled', 'rejected', 'expired', 'no_show'],
        affected_columns=[TableReference(table_schema='public', table_name='bookings', column_name='status')],
        enum_values_to_rename=[],
        indexes_to_recreate=[
            TableIndex(
                name='public.excl_no_overlapping_confirmed_bookings',
                definition="CREATE INDEX excl_no_overlapping_confirmed_bookings ON public.bookings USING gist (vehicle_id, daterange(start_date, end_date, '[)'::text)) WHERE ((status = ANY (ARRAY['confirmed'::bookingstatus, 'active'::bookingstatus])) AND (deleted_at IS NULL))",
            ),
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='bookingstatus',
        new_values=['pending_payment', 'pending_approval', 'confirmed', 'active', 'completed', 'cancelled', 'rejected', 'no_show'],
        affected_columns=[TableReference(table_schema='public', table_name='bookings', column_name='status')],
        enum_values_to_rename=[],
        indexes_to_recreate=[
            TableIndex(
                name='public.excl_no_overlapping_confirmed_bookings',
                definition="CREATE INDEX excl_no_overlapping_confirmed_bookings ON public.bookings USING gist (vehicle_id, daterange(start_date, end_date, '[)'::text)) WHERE ((status = ANY (ARRAY['confirmed'::bookingstatus, 'active'::bookingstatus])) AND (deleted_at IS NULL))",
            ),
        ],
    )
    # ### end Alembic commands ###
