"""addes deleted_at instead of is_deleted

Revision ID: 2cf04ebfeb1c
Revises: bd6ff4416128
Create Date: 2026-08-24 14:34:49.350428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf04ebfeb1c'
down_revision: Union[str, Sequence[str], None] = 'bd6ff4416128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_categories', 'deleted_at')
    # ### end Alembic commands ###
