"""update_coupons_model

Revision ID: 610145f13dd6
Revises: 04561d9cc8f7
Create Date: 2026-10-03 12:18:37.480941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610145f13dd6'
down_revision: Union[str, Sequence[str], None] = '04561d9cc8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_coupons_percentage_max', 'coupons', "discount_type <> 'percentage' OR discount_value <= 100")
    op.create_check_constraint('ck_coupons_usage_within_limit', 'coupons', 'max_usage IS NULL OR usage_count <= max_usage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_coupons_usage_within_limit', 'coupons', type_='check')
    op.drop_constraint('ck_coupons_percentage_max', 'coupons', type_='check')
    # ### end Alembic commands ###
