"""added deleted_at to coupon

Revision ID: 6d17cc184211
Revises: 7dd7bd20c2a9
Create Date: 2026-08-24 14:52:06.403399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d17cc184211'
down_revision: Union[str, Sequence[str], None] = '7dd7bd20c2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'deleted_at')
    # ### end Alembic commands ###
