"""created refund policy tiers

Revision ID: 990f8a4dd8d1
Revises: ead949b7e149
Create Date: 2026-09-25 23:56:30.243357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990f8a4dd8d1'
down_revision: Union[str, Sequence[str], None] = 'ead949b7e149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund_policy_tiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hours_before_pickup', sa.Integer(), nullable=False),
    sa.Column('refund_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('hours_before_pickup >= 0', name='ck_hours_before_pickup_non_negative'),
    sa.CheckConstraint('refund_percentage >= 0 AND refund_percentage <= 100', name='ck_refund_percentage_range'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_policy_tiers')
    # ### end Alembic commands ###
