"""add is_deleted field

Revision ID: bac2b740bdde
Revises: 0f87eacfee23
Create Date: 2026-08-12 16:03:30.088808

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bac2b740bdde"
down_revision: str | Sequence[str] | None = "0f87eacfee23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "audit_logs", ["id"])
    op.create_unique_constraint(None, "booking_status_history", ["id"])
    op.create_unique_constraint(None, "bookings", ["id"])
    op.create_unique_constraint(None, "condition_report_images", ["id"])
    op.create_unique_constraint(None, "condition_reports", ["id"])
    op.create_unique_constraint(None, "coupon_usages", ["id"])
    op.create_unique_constraint(None, "coupons", ["id"])
    op.create_unique_constraint(None, "locations", ["id"])
    op.create_unique_constraint(None, "maintenance_blocks", ["id"])
    op.create_unique_constraint(None, "notifications", ["id"])
    op.create_unique_constraint(None, "payments", ["id"])
    op.create_unique_constraint(None, "reviews", ["id"])
    op.add_column(
        "users",
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.create_unique_constraint(None, "users", ["id"])
    op.create_unique_constraint(None, "vehicle_categories", ["id"])
    op.create_unique_constraint(None, "vehicle_images", ["id"])
    op.create_unique_constraint(None, "vehicles", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vehicles", type_="unique")
    op.drop_constraint(None, "vehicle_images", type_="unique")
    op.drop_constraint(None, "vehicle_categories", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_deleted")
    op.drop_constraint(None, "reviews", type_="unique")
    op.drop_constraint(None, "payments", type_="unique")
    op.drop_constraint(None, "notifications", type_="unique")
    op.drop_constraint(None, "maintenance_blocks", type_="unique")
    op.drop_constraint(None, "locations", type_="unique")
    op.drop_constraint(None, "coupons", type_="unique")
    op.drop_constraint(None, "coupon_usages", type_="unique")
    op.drop_constraint(None, "condition_reports", type_="unique")
    op.drop_constraint(None, "condition_report_images", type_="unique")
    op.drop_constraint(None, "bookings", type_="unique")
    op.drop_constraint(None, "booking_status_history", type_="unique")
    op.drop_constraint(None, "audit_logs", type_="unique")
    # ### end Alembic commands ###
