"""add is_active field to vechicle category table

Revision ID: bd6ff4416128
Revises: d32c89afdc07
Create Date: 2026-08-22 16:44:27.170328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6ff4416128'
down_revision: Union[str, Sequence[str], None] = 'd32c89afdc07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_categories', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_categories', 'is_active')
    # ### end Alembic commands ###
